org: rickydixon3
service: nexus

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: arn:aws:s3:::nexus-raw-articles-rickydixon3/*
        - Effect: Allow
          Action: s3:GetObject
          Resource: arn:aws:s3:::nexus-raw-articles-rickydixon3/*
        - Effect: Allow
          Action: secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:us-east-1:512830091587:secret:nexus/api-keys-mxfDGf
        - Effect: Allow
          Action: secretsmanager:GetSecretValue
          Resource: arn:aws:secretsmanager:us-east-1:512830091587:secret:nexus/db-credentials-ksmwNm


custom:
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false3

    
functions:
  ingest:
    handler: ingest.ingest
    timeout: 300
    events:
      - schedule: rate(6 hours)

  normalize:
    handler: normalize.normalize
    timeout: 60

  embed:
    handler: handler.embed

  ragHandler:
    handler: handler.rag_query
    events:
      - httpApi:
          path: /query
          method: post

  listArticles:
    handler: handler.list_articles
    events:
      - httpApi:
          path: /articles
          method: get

plugins:
  - serverless-python-requirements