# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rickydixon3
# "service" is the name of this project. This will also be added to your AWS resource names.
service: nexus

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
